[project]
name = "quiz-application"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "argon2-cffi>=23.1.0",
    "django>=5.2.1",
    "passlib>=1.7.4",
]

[dependency-groups]
dev = [
    "bcrypt>=4.3.0",
]
