# Generated by Django 5.2.1 on 2025-06-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_alter_quiz_created_by_alter_response_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz'),
            preserve_default=False,
        ),
    ]
